services:
  notifications-service:
    image: samarkinivan/notifications-service:latest
    container_name: notifications-service
    restart: on-failure
    environment:
      APP_PORT: 8084
      MAIL_HOST: 'smtp.gmail.com'
      MAIL_USER: 'samarkin20022002@gmail.com'
      MAIL_PASSWORD: 'dasirmpudrndcqsj'
      MAIL_FROM: 'samarkin20022002@gmail.com'
      MAIL_PORT: 587
      RMQ_QUEUE: 'notifications-queue'
      RMQ_URL: 'amqp://default_user:default_password@rabbitmq:5672'
    ports:
      - '8084:8084'
    networks:
      - app-network

networks:
  app-network:
    external: true
